INSERT INTO ezc_wf_pricing_conditions (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1003,1,'PUR_PERSON','PUR_PERSON','LE',0);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,2,'LEADBUYER','LEADBUYER','LE',0);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,3,'SITEFI','SITEFI','LE',0);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,4,'SITEHD','SITEHD','LE',500000);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,5,'SCMHD','SCMHD','LE',999999);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,6,'BUHEAD','BUHEAD','LE',0);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,7,'FIHEAD','FIHEAD','LE',75000000);
INSERT INTO `` (`EWPC_TEMPLATE`,`EWPC_LEVEL`,`EWPC_ROLE`,`EWPC_GROUP`,`EWPC_QCF_FLAG`,`EWPC_QCF_RELEASE`) VALUES (1001,8,'CEO','CEO','GE',75000000);

//3050000005
