NA CHANGES:
-----------------------
W9 FORM SHOULD BE MANDATORY FOR ALL ENTITIES EXCEPT JDI(4500) AND CMO_SPOKANE(7501)
W8 FORM SHOULD BE MANDATORY FOR CADISTA(4101)
TYPE OF VENDOR SHOULD NOT BE MANDOTORY FOR CADISTA(4101)
FREE TEXT BOX NEEDS TO BE PROVIDED FOR PAYMENT TERMS
ONE RADIO BUTTON NEEDS TO BE PROVIDED IN BANK DETAILS TAB TO SELECT TYPE OF PAYMENT MODE
CANCELLED CHEQUE FEILD HAS BEEN PROVIDED
PAYMENT TERMS DROPDOWN HAS BEEN ENABLED IN INITIATOR LOGIN.


