#jco2.r3_no_of_conn=100
#jco2.r3_client=900
#jco2.r3_user_id=ATHINK
#jco2.r3_passwd=Hckt@2023
#jco2.r3_host=10.1.2.178
#jco2.r3_sys_no=31

jco2.r3_no_of_conn=100
jco2.r3_client=000
jco2.r3_user_id=changeme
jco2.r3_passwd=changeme
jco2.r3_host=localhost
jco2.r3_sys_no=00


spring.main.allow-bean-definition-overriding=true



spring.jpa.properties.hibernate.jpa.show-sql=true

purge.cron.expression=0 0 5 * * ?

product.cron.expression=0 35 12 ? * *

################### JavaMail Configuration ##########################
support.email=noreply@aragen.com
spring.mail.host=smtp.office365.com
spring.mail.port=587
#spring.mail.protocol=smtps
spring.mail.username=changeme
spring.mail.password=changeme


# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true
#
#spring.mail.properties.mail.transport.protocol=smtps
#spring.mail.properties.mail.smtps.auth=true
#spring.mail.properties.mail.smtps.starttls.enable=true
#spring.mail.properties.mail.smtps.timeout=8000

mail.fromaddress=changeme@domain.com

mail.ccmail=changeme@domain.com

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.hibernate=INFO
logging.file.path=./logs
logging.file.name=app.log
logging.level.com.ezc.outsrc.webapp=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#spring.h2.console.enabled=true
logging.level.org.springframework=ERROR

management.endpoints.web.exposure.include=*

spring.thymeleaf.cache: false
spring.thymeleaf.check-template=true
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

spring.mvc.static-path-pattern=/**
server.port=8081


logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari.Hikari=INFO



## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

upload.path=./uploads
app.file.upload-dir=./uploads



city=Hyderabad,Chennai,Delhi,Mumbai,Banglore,Cochin,Vijayawada

site.url=localhost:8082
session.timeout=7200
server.servlet.session.timeout=7200s
#server.tomcat.max-http-post-size=6291456
server.servlet.session.cookie.secure=true



# Server properties
server.tomcat.max-http-post-size=100000000
server.tomcat.max-swallow-size=100000000

server.tomcat.maxParameterCount=30000

logging.level.org.hibernate.orm.jdbc.bind=TRACE