upload.path=C:\\Users\\arin.jain\\ehs permannent img
upload-dir=C:\\Users\\arin.jain\\ehs permannent img


app.file.upload-dir=C:\\Users\\arin.jain\\OneDrive - The Hackett Group, Inc\\Documents\\ehs img
file.upload.permanent-dir=C:\\Users\\arin.jain\\ehs permannent img