package com.ezc.aragenPR.webapp.dto.shared;



public class EmailFormat {

	public static String formatEmail(String type,String username,String mailTxt,String link,String regards,String btnTxt)
	{
		String mailStr = "";
		mailStr+="<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>";
		mailStr+="<html xmlns='http://www.w3.org/1999/xhtml'>";
		mailStr+="<head>";
		mailStr+="  <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />";
		mailStr+="  <title>CEAT</title>";
		mailStr+="  <style type='text/css'>";
		mailStr+="  body {margin: 0; padding: 0; min-width: 100%!important;}";
		mailStr+="  img {height: auto;}";
		mailStr+="  .content {width: 100%; max-width: 600px;}"; 
		mailStr+="  .header {padding: 40px 30px 20px 30px;}";
		mailStr+="  .innerpadding {padding: 30px 30px 30px 30px;}";
		mailStr+="  .borderbottom {border-bottom: 1px solid #f2eeed;}";
		mailStr+="  .subhead {font-size: 30px; color: #d21919; font-family: sans-serif;}";
		mailStr+="  .h1, .h2, .bodycopy {color: #153643; font-family: sans-serif;}";
		mailStr+="  .h1 {font-size: 33px; line-height: 38px; font-weight: bold;}";
		mailStr+="  .h2 {padding: 0 0 15px 0; font-size: 24px; line-height: 28px; font-weight: bold;}";
		mailStr+="  .bodycopy {font-size: 16px; line-height: 22px;}";
		mailStr+="  .button {text-align: center; font-size: 18px; font-family: sans-serif; font-weight: bold; padding: 0 30px 0 30px;}";
		mailStr+="  .button a {color: #ffffff; text-decoration: none;}";
		mailStr+="  .footer {padding: 20px 30px 15px 30px;}";
		mailStr+="  .footercopy {font-family: sans-serif; font-size: 14px; color: #ffffff;}";
		mailStr+="  .footercopy a {color: #ffffff; text-decoration: underline;}";
		mailStr+="  @media only screen and (max-width: 550px), screen and (max-device-width: 550px) {";
		mailStr+="  body[yahoo] .hide {display: none!important;}";
		mailStr+="  body[yahoo] .buttonwrapper {background-color: transparent!important;}";
		mailStr+="  body[yahoo] .button {padding: 0px!important;}";
		mailStr+="  body[yahoo] .button a {background-color: #e05443; padding: 15px 15px 13px!important;}";
		mailStr+="  body[yahoo] .unsubscribe {display: block; margin-top: 20px; padding: 10px 50px; background: #2f3942; border-radius: 5px; text-decoration: none!important; font-weight: bold;}";
		mailStr+="  }";
		mailStr+="  /*@media only screen and (min-device-width: 601px) {";
		mailStr+="    .content {width: 600px !important;}";
		mailStr+="    .col425 {width: 425px!important;}";
		mailStr+="    .col380 {width: 380px!important;}";
		mailStr+="    }*/";
		mailStr+="";
		mailStr+="  </style>";
		mailStr+="</head>";
		mailStr+="<body yahoo bgcolor='#f6f8f1'>";
		mailStr+="<table width='100%' bgcolor='#f6f8f1' border='0' cellpadding='0' cellspacing='0'>";
		mailStr+="<tr>";
		mailStr+="  <td>";
		mailStr+="    <!--[if (gte mso 9)|(IE)]>";
		mailStr+="      <table width='600' align='center' cellpadding='0' cellspacing='0' border='0'>";
		mailStr+="        <tr>";
		mailStr+="          <td>";
		mailStr+="    <![endif]-->";
		mailStr+="    <table bgcolor='#ffffff' class='content' align='center' cellpadding='0' cellspacing='0' border='0'>";
		mailStr+="      <tr>";
		mailStr+="        <td bgcolor='#efe9e9' class='header'>";
		mailStr+="          <table width='70' align='left' border='0' cellpadding='0' cellspacing='0'>";
		mailStr+="            <tr>";
		mailStr+="              <td height='70' style='padding: 0 20px 20px 0;'>";
		mailStr+="                <img class='fix' src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/icon.gif' width='70' height='70' border='0' alt='' />";
		mailStr+="              </td>";
		mailStr+="            </tr>";
		mailStr+="          </table>";
		mailStr+="          <!--[if (gte mso 9)|(IE)]>";
		mailStr+="            <table width='425' align='left' cellpadding='0' cellspacing='0' border='0'>";
		mailStr+="              <tr>";
		mailStr+="                <td>";
		mailStr+="          <![endif]-->";
		mailStr+="          <table class='col425' align='left' border='0' cellpadding='0' cellspacing='0' style='width: 100%; max-width: 425px;'>";
		mailStr+="            <tr>";
		mailStr+="              <td height='70'>";
		mailStr+="                <table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		mailStr+="                  <tr>";
		mailStr+="                    <td class='subhead' style='padding: 0 0 0 3px;'>";
		mailStr+="                      <b>CEAT</b>";
		mailStr+="                    </td>";
		mailStr+="                  </tr>";
		mailStr+="                  <tr>";
		mailStr+="                    <td class='h1' style='padding: 5px 0 0 0;'>";
		mailStr+=                      type;
		mailStr+="                    </td>";
		mailStr+="                  </tr>";
		mailStr+="                </table>";
		mailStr+="              </td>";
		mailStr+="            </tr>";
		mailStr+="          </table>";
		mailStr+="          <!--[if (gte mso 9)|(IE)]>";
		mailStr+="                </td>";
		mailStr+="              </tr>";
		mailStr+="          </table>";
		mailStr+="          <![endif]-->";
		mailStr+="        </td>";
		mailStr+="      </tr>";
		mailStr+="      <tr>";
		mailStr+="        <td class='innerpadding borderbottom'>";
		mailStr+="          <table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		mailStr+="            <tr>";
		mailStr+="              <td class='h2'>";
		mailStr+="                Dear "+username+",";
		mailStr+="              </td>";
		mailStr+="            </tr>";
		mailStr+="            <tr>";
		mailStr+="              <td class='bodycopy'>";
		mailStr+="                "+mailTxt;
		mailStr+="              </td>";
		mailStr+="            </tr>";
		mailStr+="          </table>";
		mailStr+="        </td>";
		mailStr+="      </tr>";
		if(link != null && !"null".equals(link)  && !"".equals(link))
		{
			mailStr+="      <tr>";
			mailStr+="		<td style='padding: 20px 0 0 0;' align='center'>";
			mailStr+="		  <table class='buttonwrapper' bgcolor='#e05443' border='0' cellspacing='0' cellpadding='0'>";
			mailStr+="			<tr>";
			mailStr+="			  <td class='button' height='45'>";
			mailStr+="				<a href='"+link+"'>"+btnTxt+"</a>";
			mailStr+="			  </td>";
			mailStr+="			</tr>";
			mailStr+="		  </table>";
			mailStr+="		</td>";
			mailStr+="      </tr>";
			mailStr+="       <tr>";
			mailStr+="      	<td class='innerpadding borderbottom'>";
			mailStr+="      	<table width='100%' border='0' cellspacing='0' cellpadding='0'>";
			mailStr+="      		<tr>";
			mailStr+="      			<td align='center'><b>Link Expires In 3 Days</b></td>";
			mailStr+="      		</tr>";
			mailStr+="      	</table>";
			mailStr+="      	</td>";
			mailStr+="      </tr>";
		}
		mailStr+="    </table>";
		mailStr+="    <!--[if (gte mso 9)|(IE)]>";
		mailStr+="          </td>";
		mailStr+="        </tr>";
		mailStr+="    </table>";
		mailStr+="    <![endif]-->";
		mailStr+="    </td>";
		mailStr+="  </tr>";
		mailStr+="</table>";
		mailStr+="</body>";
		mailStr+="</html>";
		return mailStr;
	}
}
