name: Build WAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build WAR
        run: .\mvnw.cmd clean package
        shell: powershell

      - name: Create Deployments Folder
        shell: powershell
        run: |
          if (!(Test-Path "C:\Deployments")) {
              New-Item -ItemType Directory -Path "C:\Deployments" | Out-Null
          }

      - name: Backup Existing ROOT.war
        shell: powershell
        run: |
          $dest = "C:\Deployments\ROOT.war"

          if(Test-Path $dest)
          {
             $date = Get-Date -Format "yyyyMMdd_HHmmss"
             Rename-Item $dest "ROOT_BACKUP_$date.war"
          }

      - name: Copy WAR as ROOT.war
        shell: powershell
        run: |
          $war = Get-ChildItem target\*.war | Select-Object -First 1
          Copy-Item $war.FullName "C:\Deployments\ROOT.war" -Force